# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: 12 0/2 * * * # 12 mins, every 2 hours
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd ./.github/workflows/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Get the number of infecteds by states from Wikipedia
      run: |
        cd ./
        python dataFromWikipedia.py
    - name: Get the number of nationwide total from The Star Online
      run: |
        cd ./
        python dataFromStarOnline.py
    - name: Export the above results to GitHub repository
      env:
        GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git config user.email "$GIT_OWNER_EMAIL"
        git config user.name "drxyzw"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -a -m "Automatically updating daily CSV data"
          git remote rm origin
          git remote add origin https://drxyzw:$PUSH_TOKEN@github.com/drxyzw/WuhanCoronavirus-Malaysia.git
          git push origin HEAD:master
        else
          echo 'there is no change'
        fi

